all: Pokemon

Pokemon: main.cpp entrenacabra.cpp pokegod2.cpp Batalla.cpp
	g++ main.cpp entrenacabra.cpp pokegod2.cpp Batalla.cpp -o Pokemon
	

clean:
	rm -f Pokemon

run: Pokemon
	./Pokemon